language: rust
rust: stable
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu

install:
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git japaric/cross --force
  - source ~/.cargo/env || true

script:
  - cross test --target $TARGET
  - cross test --target $TARGET --no-default-features --features kyber768
  - cross test --target $TARGET --no-default-features --features kyber1024

cache: cargo
